# Generated by Django 4.1.3 on 2022-11-18 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accidents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highway', models.CharField(max_length=10)),
                ('month', models.CharField(max_length=10)),
                ('day_night', models.CharField(max_length=10)),
                ('marker', models.IntegerField()),
                ('fatal_non', models.CharField(max_length=10)),
            ],
        ),
    ]
